### ISSUE TITLE
Unknown Error when trying to launch BSG Launcher.

### ISSUE THREAD

**Issue by AzyWng** [MadByteDE/SPT-Linux-Guide#2]
## Issue Report

**Distro**:
EndeavourOS

**Install method**:
Lutris Installer

**EFT Version**:
I couldn't install SPT.

**Mod Version**:
Was trying to install through the Lutris Installer.

## Description
Unknown error when trying to launch BSG Launcher

## Attachments
https://endeavour.kamprad.net/pastebin/?5621670bcf1104e9#A42ya9gVGzncY4budw1c7BBLNhh2zHLambcy9optab67

**Comment by MadByteDE** [comment]
I don't see an issue with the log you provided. you can get a wine log by enabling `output debugging info` in the global runner options:
![grafik](https://github.com/user-attachments/assets/776cb8db-b383-4174-95ca-cf4493bee3e1)

Also what exactly doesn't work, what happens?

**Comment by AzyWng** [comment]
Sorry, I had to change my operating system following an error during an update, so I don't really have the ability to try to reproduce the bug.

If I do give installing SPTarkov another shot, I'll be sure to let you know of any issues that arise.
